AWSSageMakerRuntime Update models to latest
aws-amplify/aws-sdk-ios pull request #5103
Opened 2023-11-29 18:55 UTC by awsmobilesdk

AWSSageMakerRuntime Update models to latest

2023-12-28 17:06 UTC, lawmicha approved these changes

2023-12-28 18:11 UTC, lawmicha requested changes
```
❌  /Users/runner/work/aws-sdk-ios/aws-sdk-ios/AWSSageMakerRuntime/AWSSageMakerRuntimeModel.h:310:32: nullability specifier '_Nullable' cannot be applied to non-pointer type 'int'

@property (nonatomic, strong)  _Nullable internalStreamFailure;
                               ^
```

2023-12-28 18:12 UTC, lawmicha commented
See comments in https://github.com/aws-amplify/aws-sdk-ios/pull/4936 as well

2024-04-04 17:33 UTC, ruisebas commented
Closing this PR as it can't be merged as is due to the compilation issues.

When a new model update for **AWSSageMakeRuntime** is generated, the new PR won't have these issues and will be merged

2024-04-04 17:33 UTC, closed without merging